version: "3.5" 
services:
    nginx:
        image: nginx:1.15-alpine
        networks:
            - fortalecimiento
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        networks:
            - fortalecimiento
        container_name: certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    php-fpm:
        build: data/php-fpm
        networks:
            - fortalecimiento
        container_name: serverphp
        working_dir: /var/www/certbot
        volumes:
            - ./data/certbot/www:/var/www/certbot
            - ./data/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini 
networks:
    fortalecimiento:
        external:
            name: fortalecimiento
